repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0  # Use the latest stable version from https://github.com/astral-sh/ruff/releases
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
        pass_filenames: false
      # Run the formatter.
      - id: ruff-format
