[tool.ruff]
# Enable all built-in rules
select = ["E", "F", "W", "C", "N", "Q", "RUF100", "RET", "S", "T", "A", "B", "D", "I"]

# Exclude specific directories
exclude = [
    "__pycache__",
    ".git",
    "static",
    "templates"
]

# Set the maximum line length
line-length = 88

# Ignore incompatible rules
ignore = [
    "D203",  # one-blank-line-before-class
    "D213",  # multi-line-summary-second-line
]

# Add any additional configuration options as needed
