[tool.ruff]
# Global settings
exclude = [
    "__pycache__",
    ".git",
    "static",
    "templates"
]
line-length = 88

[tool.ruff.lint]
# Enable all built-in rules
select = ["E", "F", "W", "C", "N", "Q", "RUF100", "RET", "S", "T", "A", "B", "D", "I"]

# Ignore incompatible rules
ignore = [
    "D203",  # one-blank-line-before-class
    "D213",  # multi-line-summary-second-line
]

# Add any additional configuration options as needed
